GET http://localhost:8000/cases

###

GET http://localhost:8000/cases/

###

POST http://localhost:8000/cases
Content-Type: application/json

{
    "projectName": "Plantacle",
    "clientName": "Blue City",
    "summary": "Make your own compost!",
    "description": "For this client we created a composting-module and an app."
}

###

DELETE  http://localhost:8000/cases/5de042a71eada53bd874a359

###

PATCH   http://localhost:8000/cases/5de043fcec6fd029f46c6159
Content-Type: application/json

{
    "clientName": "Blue City, Hogeschool Rotterdam"
}

###

OPTIONS   http://localhost:8000/cases/5de042a71eada53bd874a359

###
POST http://145.24.222.215:8000/cases
Content-Type: application/json

{
    "projectName": "Castlevania: Holy Fires",
    "clientName": "Own project",
    "summary": "A remake of The Castlevania Adventure (1989)",
    "description": "A fangame created to celebrate the 30th anniversary of a very underrated Castlevania game."
}

###

GET http://145.24.222.215:8000/cases

###