GET http://localhost:8000/cases

###

GET http://localhost:8000/cases/5de04403ec6fd029f46c615a

###

POST http://localhost:8000/cases
Content-Type: application/json

{
    "projectName": "Plantacle",
    "clientName": "Blue City",
    "summary": "Make your own compost!",
    "description": "For this client we created a composting-module and an app."
}

###

DELETE  http://localhost:8000/cases/5de042a71eada53bd874a359

###

PATCH   http://localhost:8000/cases/5de043fcec6fd029f46c6159
Content-Type: application/json

{
    "clientName": "Blue City, Hogeschool Rotterdam"
}

